import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import clsx from "clsx";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Bookme",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
      <body className={clsx(inter.className, 'flex justify-center items-center')}>
        <div className="flex flex-col max-w-screen-sm w-full relative h-screen md:border-x border-divider">
          <header className="px-4 pb-3 pt-12 border-b border-divider">
            <div className="flex justify-between">
              <Image 
                src='/brand-logo.jpg' 
                width={130} 
                height={40} 
                alt="Brand"
                style={{
                  objectFit: 'contain'
                }}
              />
              <button className="btn-teritary">Account</button>
            </div>
          </header>
          <main className="flex flex-col min-h-0 flex-1">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
